import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowLeft, CheckCircle2, Clock3, FileWarning, Laptop, Loader2, MonitorUp, Network, RefreshCw, ShieldAlert, ShieldCheck, TerminalSquare } from "lucide-react";
import { Link, useRoute } from "wouter";

function formatDate(value?: Date | string | null) {
  return value ? new Date(value).toLocaleString("ko-KR", { year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "기록 없음";
}

export default function AgentDetail() {
  const [, params] = useRoute("/agents/:id");
  const agentId = Number(params?.id);
  const detail = trpc.security.agentDetail.useQuery({ agentId }, { enabled: Number.isFinite(agentId) && agentId > 0, refetchInterval: 30_000 });
  const agent = detail.data;

  if (detail.isLoading) return <div className="detail-loading"><Loader2 className="h-5 w-5 animate-spin" />에이전트 상세 정보를 불러오는 중입니다.</div>;
  if (!agent) return <div className="empty-state"><div className="empty-icon"><Laptop className="h-6 w-6" /></div><strong>에이전트를 찾을 수 없습니다.</strong><p>목록에서 유효한 에이전트를 선택해 주세요.</p><Button asChild className="mt-4"><Link href="/agents"><ArrowLeft className="mr-2 h-4 w-4" />에이전트 목록</Link></Button></div>;

  const statusLabel = agent.effectiveStatus === "online" ? "온라인" : agent.effectiveStatus === "degraded" ? "주의" : "오프라인";
  return (
    <div className="page-stack">
      <div className="detail-back"><Link href="/agents"><ArrowLeft className="h-4 w-4" /> 에이전트 목록</Link><Button variant="ghost" size="sm" onClick={() => detail.refetch()}><RefreshCw className="mr-2 h-4 w-4" />새로고침</Button></div>
      <section className="agent-detail-hero"><div className="agent-hero-main"><div className={`agent-hero-icon ${agent.effectiveStatus}`}><Laptop className="h-7 w-7" /></div><div><div className="eyebrow">Managed endpoint / {agent.agentKey}</div><h1>{agent.hostName}</h1><div className="agent-hero-meta"><span className={`inline-status ${agent.effectiveStatus}`}><span />{statusLabel}</span><span>{agent.siteName}</span><span>{agent.ipAddress ?? "IP 미수집"}</span></div></div></div><div className="agent-hero-actions"><Badge className={`status-badge ${agent.effectiveStatus}`}>{statusLabel}</Badge><span className="last-seen"><Clock3 className="h-3.5 w-3.5" />최근 {formatDate(agent.lastHeartbeatAt)}</span></div></section>
      <section className="detail-metric-grid"><Card className="detail-metric-card"><div className="detail-metric-icon green"><ShieldCheck className="h-4 w-4" /></div><span>Defender 보호</span><strong>{agent.defenderEnabled ? "활성" : "확인 필요"}</strong><small>{agent.signatureVersion ? `서명 ${agent.signatureVersion}` : "서명 버전 미수집"}</small></Card><Card className="detail-metric-card"><div className="detail-metric-icon blue"><Network className="h-4 w-4" /></div><span>에이전트 버전</span><strong>{agent.agentVersion ?? "-"}</strong><small>{agent.osVersion ?? "OS 정보 미수집"}</small></Card><Card className="detail-metric-card"><div className="detail-metric-icon amber"><FileWarning className="h-4 w-4" /></div><span>Quarantine</span><strong>{agent.quarantine.length}건</strong><small>최근 20건 기준</small></Card><Card className="detail-metric-card"><div className="detail-metric-icon violet"><TerminalSquare className="h-4 w-4" /></div><span>원격 명령</span><strong>{agent.commands.length}건</strong><small>최근 20건 기준</small></Card></section>
      <section className="dashboard-grid detail-content-grid"><Card className="panel-card"><CardHeader className="panel-header"><div><div className="eyebrow">Defender telemetry</div><CardTitle>보호기록 이력</CardTitle></div><ShieldCheck className="h-5 w-5 text-emerald-500" /></CardHeader><CardContent className="p-0">{agent.defenderHistory.length === 0 ? <div className="empty-state compact"><div className="empty-icon"><ShieldCheck className="h-5 w-5" /></div><div><strong>Defender 수집 이력이 없습니다.</strong><p>에이전트 heartbeat가 수신되면 이력과 서명 버전이 누적됩니다.</p></div></div> : <div className="activity-list">{agent.defenderHistory.slice(0, 8).map(item => <div className="activity-item" key={item.id}><span className="activity-dot green" /><div><strong>{item.realtimeProtection ? "실시간 보호 활성" : "실시간 보호 확인 필요"}</strong><span>{item.signatureVersion ?? "서명 버전 미수집"} · {formatDate(item.collectedAt)}</span></div><Badge variant="outline">{item.antivirusEnabled ? "활성" : "비활성"}</Badge></div>)}</div>}</CardContent></Card><Card className="panel-card"><CardHeader className="panel-header"><div><div className="eyebrow">Recent operations</div><CardTitle>최근 작업</CardTitle></div><Activity className="h-5 w-5 text-violet-500" /></CardHeader><CardContent className="p-0">{agent.commands.length === 0 && agent.sessions.length === 0 ? <div className="empty-state compact"><div className="empty-icon"><Activity className="h-5 w-5" /></div><div><strong>최근 원격 작업이 없습니다.</strong><p>검사 명령 또는 RDP 세션이 생성되면 이곳에 나타납니다.</p></div></div> : <div className="activity-list">{agent.commands.slice(0, 5).map(item => <div className="activity-item" key={`command-${item.id}`}><span className="activity-dot violet" /><div><strong>{item.commandType}</strong><span>{formatDate(item.requestedAt)}</span></div><Badge variant="outline">{item.status}</Badge></div>)}{agent.sessions.slice(0, 5).map(item => <div className="activity-item" key={`session-${item.id}`}><span className="activity-dot blue" /><div><strong><MonitorUp className="mr-1 inline h-3.5 w-3.5" />RDP {item.path === "external" ? "External" : "Internal"}</strong><span>{formatDate(item.startedAt)}</span></div><Badge variant="outline">세션</Badge></div>)}</div>}</CardContent></Card></section>
      <Card className="panel-card"><CardHeader className="panel-header"><div><div className="eyebrow">Endpoint profile</div><CardTitle>에이전트 연결 정보</CardTitle></div></CardHeader><CardContent className="profile-grid"><div><span>호스트명</span><strong>{agent.hostName}</strong></div><div><span>사업장</span><strong>{agent.siteName}</strong></div><div><span>IP 주소</span><strong>{agent.ipAddress ?? "-"}</strong></div><div><span>운영체제</span><strong>{agent.osVersion ?? "-"}</strong></div><div><span>등록 시각</span><strong>{formatDate(agent.createdAt)}</strong></div><div><span>마지막 업데이트</span><strong>{formatDate(agent.updatedAt)}</strong></div></CardContent></Card>
    </div>
  );
}
